plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'com.batista.stickies.Main'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation('com.formdev:flatlaf:3.4.1')
    implementation("org.xerial:sqlite-jdbc:3.53.2.1")
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

